---
- name: install MySQL server
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - mysql-server
    - python-mysqldb
#
- name: start MySQL service
  service: name=mysql state=started enabled=yes
#
- name: update MySQL root password
  mysql_user:
    name: "{{ mysql_root_name }}" 
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_name }}"
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
      - "{{ hostvars[groups['webservers'][0]]['ansible_eth1']['ipv4']['address'] }}"
  notify: restart mysql
#
- name: Copy MySQL configuration file
  template: 
    src: my.cnf.j2 
    dest: /etc/mysql/my.cnf 
    owner: root 
    mode: 0600
  notify: restart mysql